apiVersion: v1
kind: Service
metadata:
  name: nodejs-front-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31026
  selector:
    environment: Dev-UI  

